# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181124_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainPage_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='mainpage')),
            ],
        ),
    ]
