# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_mainpage_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inovel_name', models.CharField(max_length=32)),
                ('inovel_cover', models.ImageField(upload_to='cover_img')),
                ('inovel_type', models.CharField(max_length=12)),
            ],
        ),
    ]
