# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-27 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_inovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
