# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='inovel',
            name='inovel_author',
            field=models.CharField(default='辰东', max_length=32),
        ),
    ]
