# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-06 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_inovel_inovel_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inovel',
        ),
        migrations.DeleteModel(
            name='mainPage_img',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
