# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-06 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0007_auto_20181206_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.TextField(blank=True, null=True)),
                ('book_name', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('book_state', models.TextField(blank=True, null=True)),
                ('book_infomation', models.TextField(blank=True, null=True)),
                ('book_one_title', models.TextField(blank=True, null=True)),
                ('book_two_title', models.TextField(blank=True, null=True)),
                ('fontnumber', models.TextField(blank=True, null=True)),
                ('clicknumber', models.TextField(blank=True, null=True)),
                ('recommandnumber', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'novel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('faceimg', models.ImageField(upload_to='images')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
